#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("K9Control4.Resource", IsApplication=true)]

namespace K9Control4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int down = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ears = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int eyes = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int eyesFlash = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int greenButton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int greenDark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int joystick = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int K9PLAN1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int laserFiring = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int laserIn = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int laserOut = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int orangeButton = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int orangeDark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int redButton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int redDark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int tail2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int target2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int target3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int target4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int up = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001f
			public const int bt1978 = 2131034143;
			
			// aapt resource value: 0x7f050018
			public const int btAffirmative = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int btBeGood = 2131034140;
			
			// aapt resource value: 0x7f050002
			public const int btConnect = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int btDiagnostic = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int btDisconnect = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int btEars = 2131034122;
			
			// aapt resource value: 0x7f05001e
			public const int btEfficientMachine = 2131034142;
			
			// aapt resource value: 0x7f050010
			public const int btEyesFlash = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int btEyesToggle = 2131034127;
			
			// aapt resource value: 0x7f050022
			public const int btIAmK9 = 2131034146;
			
			// aapt resource value: 0x7f05000e
			public const int btLaserIn = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int btLaserOnOff = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int btLaserOut = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int btMaster = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int btMistress = 2131034134;
			
			// aapt resource value: 0x7f050021
			public const int btNaturally = 2131034145;
			
			// aapt resource value: 0x7f050019
			public const int btNegative = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int btNoData = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int btSendTest = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int btTail = 2131034123;
			
			// aapt resource value: 0x7f050024
			public const int editText = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int imgTarget = 2131034147;
			
			// aapt resource value: 0x7f050009
			public const int rwFunctionControls1 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int rwFunctionControls2 = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int rwFunctionControls3 = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int rwFunctionControls4 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int rwSound1 = 2131034132;
			
			// aapt resource value: 0x7f050017
			public const int rwSound2 = 2131034135;
			
			// aapt resource value: 0x7f05001a
			public const int rwSound3 = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int rwSound4 = 2131034141;
			
			// aapt resource value: 0x7f050020
			public const int rwSound5 = 2131034144;
			
			// aapt resource value: 0x7f050006
			public const int tableLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int tableRow2 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int tblConnection = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int tblSoundControls = 2131034120;
			
			// aapt resource value: 0x7f050025
			public const int textView = 2131034149;
			
			// aapt resource value: 0x7f050005
			public const int txInfo = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
